name: Test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  request:
    runs-on: ubuntu-latest
    env:
      TEST_ONLY: ${{ github.event_name != 'push' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Rudder Transformation Action
        uses: pierreyveslebeau/rudderstack-repository-official@test
        with:
          metaPath: './code/meta.json'
          email: 'pierre-yves@fatmap.com'
          accessToken: ${{ secrets.ACCESS_TOKEN }}
          uploadTestArtifact: true
